### ISSUE TITLE
UnityDataTool raises an exception if non-English characters are included.

### ISSUE THREAD

**Issue by AAAAAGUGUGU3** [Unity-Technologies/UnityDataTools#14]
## Correct Behavior

Works correctly if the path is only in English

```
PS C:\Users\kotaro.nakajima\Iroiro\testDir> ..\UnityDataTool\UnityDataTool.exe analyze . -p '*.pkg' -o test.db
Processing 100% (1/1) asset.pkg
Finalizing database...

Total time: 0.339 s
```

## Error Behavior

An error will occur if Japanese or emoji are included.

```                                               
PS C:\Users\kotaro.nakajima\Iroiro\テスト> ..\UnityDataTool\UnityDataTool.exe analyze . -p '*.pkg' -o test.db

Error processing file C:\Users\kotaro.nakajima\Iroiro\テスト\asset.pkg!
System.IO.FileNotFoundException: File not found.
   at UnityDataTools.FileSystem.UnityFileSystem.HandleErrors(ReturnCode returnCode, String filename) in D:\Soft\UnityDataTools\UnityFileSystem\UnityFileSystem.cs:line 66
   at UnityDataTools.FileSystem.UnityFileSystem.MountArchive(String path, String mountPoint) in D:\Soft\UnityDataTools\UnityFileSystem\UnityFileSystem.cs:line 33
   at UnityDataTools.Analyzer.AnalyzerTool.Analyze(String path, String databaseName, String searchPattern, Boolean skipReferences) in D:\Soft\UnityDataTools\Analyzer\AnalyzerTool.cs:line 39

Finalizing database...

Total time: 0.040 s
```

```                                       
PS C:\Users\kotaro.nakajima\Iroiro\😋> ..\UnityDataTool\UnityDataTool.exe analyze . -p '*.pkg' -o test.db

Error processing file C:\Users\kotaro.nakajima\Iroiro\??\asset.pkg!
System.IO.FileNotFoundException: File not found.
   at UnityDataTools.FileSystem.UnityFileSystem.HandleErrors(ReturnCode returnCode, String filename) in D:\Soft\UnityDataTools\UnityFileSystem\UnityFileSystem.cs:line 66
   at UnityDataTools.FileSystem.UnityFileSystem.MountArchive(String path, String mountPoint) in D:\Soft\UnityDataTools\UnityFileSystem\UnityFileSystem.cs:line 33
   at UnityDataTools.Analyzer.AnalyzerTool.Analyze(String path, String databaseName, String searchPattern, Boolean skipReferences) in D:\Soft\UnityDataTools\Analyzer\AnalyzerTool.cs:line 39

Finalizing database...

Total time: 0.032 s
```

**Comment by SkowronskiAndrew** [comment]
Sorry for the long delay @kotaronakajima and thank you for the bug report.
I have reproduced and am working on a fix.
