### ISSUE TITLE
Not working on M1 mac

### ISSUE THREAD

**Issue by kabam-sjin** [Unity-Technologies/UnityDataTools#5]
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'UnityFileSystemApi' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libUnityFileSystemApi, 0x0001): tried: 'libUnityFileSystemApi' (no such file), '/usr/local/lib/libUnityFileSystemApi' (no such file), '/usr/lib/libUnityFileSystemApi' (no such file), '/Users/sjin/kbm-devspc/gitwork/UnityDataTools/UnityDataTool/bin/Release/net6.0/libUnityFileSystemApi' (no such file)
   at UnityDataTools.FileSystem.DllWrapper.Init()
   at UnityDataTools.FileSystem.UnityFileSystem.Init() in /Users/sjin/kbm-devspc/gitwork/UnityDataTools/UnityFileSystem/UnityFileSystem.cs:line 12
   at UnityDataTools.UnityDataTool.Program.Main(String[] args) in /Users/sjin/kbm-devspc/gitwork/UnityDataTools/UnityDataTool/Program.cs:line 16
```
It looks like it's missing the arm64-compatible UnityFileSystemApi.

**Comment by kabam-sjin** [comment]
Just my mistake. Wrong binaries were placed in `bin/Release/net6.0` because I was running the publish command in the root folder. It's working well to run binaries under the `bin/Release/net6.0/osx-x64` folder.
